# UR arm configuration
arm:
  arm_kinematics: "kinematics/default_kinematics.yaml"
  arm_joint_limits: "limits/joint_kinematics.yaml"
  arm_pose:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0

  gripper: "custom:no_gripper" 
  gripper_controller: "none" 
  # gripper: "weiss-wsg50" 
  # gripper_controller: "weiss-gripper" 
  # gripper: "onrobot-rg6-v2"
  # gripper_controller:  "onrobot-rg"
  gripper_pose:
    x: 0.0
    y: 0.0
    z: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # camera: "realsense-d435i"
  # camera_pose:
  #   x: 0
  #   y: 0
  #   z: 0
  #   roll: 0
  #   pitch: 0
  #   yaw: 0

  network:
    ip: "192.168.1.20" #"192.168.56.101"
    script_command_port: "50004"
    reverse_port: "50001"
    script_sender_port: "50002"
    trajectory_port: "50003"

# # Fixed cameras
# fixed_cameras_file: "fixed_cameras/dataset_collection.yaml"